### PR TITLE
First Upload of all files

### PR DESCRIPTION
**Pull request by collamaf**
let's go!

### CODE REVIEW

**Comment by kyrsjo** [comment]
Watch out, you got a few extra files here:
- #Twiss_util.C#
- MyNtuple2Geom
- db '''$ file db
db: broken symbolic link to /Users/francesco/mad/optics/fcc/hh/LATTICE_V4/Baseline
'''
- files/alice_ESDgeometry.root.ROOT.cachefile
- hbumad
- libMDISim.so
- libMyClib.so
- libMyroot5.so
- libMyroot6.so

Maybe unwanted:
- files/alice_ESDgeometry.root
- fcc_ring_v4_baseline_b2.seq
- fcc_ring_v4_baseline_b1_survey.root

**Comment by collamaf** [comment]
thank you, but nothing’s so easy!
at the moment we have to rely on several .so, so I excluded them from te git ignore, and even root files!
However, now I’m only making some try, so allow me for some mess :D
francesco
############################
Francesco Collamati Ph.D.
Istituto Nazionale di Fisica Nucleare
Laboratori Nazionali di Frascati
Divisione Acceleratori, Ed.2, stanza 111,
tel. 2340
francesco.collamati@lnf.infn.it
###########################

**Comment by kyrsjo** [comment]
Can't you build the .so files "on demand" with a script? I wasn't sure about the .root files. And some of the other files should pretty obviously not be there :)

**Comment by collamaf** [comment]
############################
Francesco Collamati Ph.D.
Istituto Nazionale di Fisica Nucleare
Laboratori Nazionali di Frascati
Divisione Acceleratori, Ed.2, stanza 111,
tel. 2340
francesco.collamati@lnf.infn.it
###########################

> Il giorno 12 mag 2016, alle ore 10:37, Kyrre Ness Sjøbæk <notifications@github.com> ha scritto:
> 
> Can't you build the .so files "on demand" with a script? I wasn't sure about the .root files. And some of the other files should pretty obviously not be there :)
> 
> 
Don’t know, we will ask to Helmut. Problem is at today some functions are stored in those library that only he can generate being based on stuff placed somewhere else in his pc. However quiet miracolously those .so seem to work even on our mac’s, so for the moment we can bo with them..
For the rest, I will refine our .gitignore :)

**Comment by kyrsjo** [comment]
Ah, ok. Seems like something that must me dealt with then.

By the way, I will edit your replies here on GitHub, since they contain a email signature containing quite a bit of information which should probably not be public.

**Pull request merged**
